# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-30 16:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    replaces = [('blog', '0001_initial'), ('blog', '0002_auto_20181129_1928'), ('blog', '0003_auto_20181129_2304'), ('blog', '0004_auto_20181129_2309'), ('blog', '0005_auto_20181129_2316'), ('blog', '0006_auto_20181130_1137'), ('blog', '0007_auto_20181130_1225'), ('blog', '0008_auto_20181130_1830'), ('blog', '0009_auto_20181130_1849'), ('blog', '0010_auto_20181130_1859'), ('blog', '0011_auto_20181130_1904')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_inhabitant', models.CharField(max_length=100)),
                ('name_of_organisation', models.CharField(max_length=30)),
                ('result', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_inhabitant', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('reason', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Reply_register',
            fields=[
                ('reply_number', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name_of_inhabitant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Reply')),
                ('result', models.TextField()),
                ('name_of_doer', models.CharField(max_length=100)),
                ('request_status', models.CharField(max_length=10)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Request_register',
            fields=[
                ('request_number', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_inhabitant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Request')),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('reason', models.TextField()),
                ('name_of_doer', models.CharField(max_length=100)),
                ('request_status', models.CharField(max_length=10)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
