# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-29 16:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='published_date',
        ),
        migrations.RemoveField(
            model_name='request',
            name='published_date',
        ),
    ]
