# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-29 20:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20181129_1928'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply_register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_number', models.BigIntegerField()),
                ('name_of_inhabitant', models.CharField(max_length=100)),
                ('result', models.TextField()),
                ('name_of_doer', models.CharField(max_length=100)),
                ('request_status', models.CharField(max_length=10)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Request_register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_number', models.BigIntegerField()),
                ('name_of_inhabitant', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('reason', models.TextField()),
                ('name_of_doer', models.CharField(max_length=100)),
                ('request_status', models.CharField(max_length=10)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='reply',
            name='name_of_inhabitant',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='reply',
            name='name_of_organisation',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='reply',
            name='title',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='request',
            name='name_of_inhabitant1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='request',
            name='title1',
            field=models.CharField(default='', max_length=20),
        ),
    ]
