# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-02 08:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_reply_name_of_organisation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply_register',
            name='name_of_inhabitant',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reply_register',
            name='reply_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Reply'),
        ),
        migrations.AlterField(
            model_name='request_register',
            name='name_of_inhabitant',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='request_register',
            name='request_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Request'),
        ),
    ]
