# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-22 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='request',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
