# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-29 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20181129_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply_register',
            name='title',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='request_register',
            name='title',
            field=models.CharField(default='', max_length=20),
        ),
    ]
