# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-22 19:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20181122_2157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='name_of_inhabitant',
            new_name='name_of_inhabitant1',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='title',
            new_name='title1',
        ),
    ]
