# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-02 08:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20181202_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply_register',
            name='name_of_inhabitant',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='reply_register',
            name='reply_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='blog.Reply'),
        ),
    ]
