# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-30 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20181129_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='name_of_inhabitant',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='request',
            name='name_of_inhabitant',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
