# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-30 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20181130_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='name_of_inhabitant',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='request',
            name='name_of_inhabitant',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
