# Generated by Django 2.1.3 on 2018-12-02 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20181202_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply_register',
            name='reply_number',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='blog.Reply'),
        ),
        migrations.AlterField(
            model_name='request_register',
            name='request_number',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='blog.Request'),
        ),
    ]
