# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-30 15:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20181130_1830'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='title',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='title',
            new_name='id',
        ),
    ]
