# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-30 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20181130_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='name_of_inhabitant',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='reply_register',
            name='reply_number',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='request',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='request',
            name='name_of_inhabitant',
            field=models.CharField(max_length=100),
        ),
    ]
