# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-30 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20181130_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='reply_register',
            name='reply_number',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='request',
            name='id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='request_register',
            name='request_number',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
